# Generated by Django 6.1 on 2026-09-03 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_vacancy_title_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.applicant')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vacancy')),
            ],
        ),
    ]
