# Generated by Django 6.1 on 2026-09-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancies', models.PositiveIntegerField(default=0)),
                ('applicants', models.PositiveIntegerField(default=0)),
                ('employers', models.PositiveIntegerField(default=0)),
                ('applications', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
