# Generated by Django 6.1 on 2026-09-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='user',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
