# Generated by Django 6.1 on 2026-09-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_statistic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employer_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default=2, verbose_name='Статус отклика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('active', 'Актуальна'), ('closed', 'Вакансия закрыта'), ('paused', 'Приостановлена')], default='Elaman', verbose_name='Статус Ваканции'),
            preserve_default=False,
        ),
    ]
