# Generated by Django 6.1 on 2026-09-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_application_employer_response_application_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус отклика'),
        ),
        migrations.AlterField(
            model_name='application',
            name='employer_response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ работодателя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
