# Generated by Django 6.1 on 2026-09-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('active', 'Актуальна'), ('closed', 'Вакансия закрыта'), ('paused', 'Приостановлена')], default='pending', max_length=20, verbose_name='Статус отклика'),
        ),
    ]
