# Generated by Django 6.1 on 2026-09-09 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_vacancy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.employer'),
            preserve_default=False,
        ),
    ]
